-- Fix auto_post_queue table - add ALL missing columns

-- Add columns (including created_at and id if missing)
ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS bot_user_id UUID;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS topic TEXT;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS tone VARCHAR(50) DEFAULT 'neutral';

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS post_id UUID;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS generated_title TEXT;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS error_message TEXT;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS tokens_used INTEGER;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE auto_post_queue
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;

-- Add foreign key constraints
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'auto_post_queue_bot_user_id_fkey'
    ) THEN
        ALTER TABLE auto_post_queue
        ADD CONSTRAINT auto_post_queue_bot_user_id_fkey
        FOREIGN KEY (bot_user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'auto_post_queue_post_id_fkey'
    ) THEN
        ALTER TABLE auto_post_queue
        ADD CONSTRAINT auto_post_queue_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_queue_status ON auto_post_queue(status);
CREATE INDEX IF NOT EXISTS idx_queue_bot_user ON auto_post_queue(bot_user_id);
CREATE INDEX IF NOT EXISTS idx_queue_created ON auto_post_queue(created_at);

-- Comments
COMMENT ON TABLE auto_post_queue IS 'Simple queue for auto-post topics';
COMMENT ON COLUMN auto_post_queue.topic IS 'Topic for AI to generate content';
COMMENT ON COLUMN auto_post_queue.tone IS 'Tone style for content generation';
COMMENT ON COLUMN auto_post_queue.status IS 'pending = waiting, completed = done, failed = error';
COMMENT ON COLUMN auto_post_queue.post_id IS 'Reference to created post';
COMMENT ON COLUMN auto_post_queue.generated_title IS 'Title generated by AI';
COMMENT ON COLUMN auto_post_queue.error_message IS 'Error message if failed';
COMMENT ON COLUMN auto_post_queue.tokens_used IS 'OpenAI tokens used';
COMMENT ON COLUMN auto_post_queue.completed_at IS 'When the topic was processed';
