-- Drop and recreate auto_post_queue table completely

DROP TABLE IF EXISTS auto_post_queue CASCADE;

CREATE TABLE auto_post_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bot_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Topic & Tone
    topic TEXT NOT NULL,
    tone VARCHAR(50) DEFAULT 'neutral',

    -- Status
    status VARCHAR(20) DEFAULT 'pending',

    -- Generated Post
    post_id UUID REFERENCES posts(id) ON DELETE SET NULL,
    generated_title TEXT,
    error_message TEXT,

    -- Metadata
    tokens_used INTEGER,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

-- Indexes
CREATE INDEX idx_queue_status ON auto_post_queue(status);
CREATE INDEX idx_queue_bot_user ON auto_post_queue(bot_user_id);
CREATE INDEX idx_queue_created ON auto_post_queue(created_at);

-- Comments
COMMENT ON TABLE auto_post_queue IS 'Simple queue for auto-post topics';
COMMENT ON COLUMN auto_post_queue.topic IS 'Topic for AI to generate content';
COMMENT ON COLUMN auto_post_queue.tone IS 'Tone style for content generation';
COMMENT ON COLUMN auto_post_queue.status IS 'pending = waiting, completed = done, failed = error';
COMMENT ON COLUMN auto_post_queue.post_id IS 'Reference to created post';
COMMENT ON COLUMN auto_post_queue.generated_title IS 'Title generated by AI';
COMMENT ON COLUMN auto_post_queue.error_message IS 'Error message if failed';
COMMENT ON COLUMN auto_post_queue.tokens_used IS 'OpenAI tokens used';
COMMENT ON COLUMN auto_post_queue.completed_at IS 'When the topic was processed';
