// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/media/confirm-upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates media record after successful frontend upload to R2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Confirm upload completion",
                "parameters": [
                    {
                        "description": "Confirm upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ConfirmUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/media/presigned-upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a presigned URL for frontend to upload files directly to R2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Generate presigned upload URL",
                "parameters": [
                    {
                        "description": "Upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PresignedUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PresignedUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/media/presigned-upload-batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates multiple presigned URLs for frontend to upload files directly to R2 (max 200 files)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Generate batch presigned upload URLs",
                "parameters": [
                    {
                        "description": "Batch upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchPresignedUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchPresignedUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/upload/confirm-batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates multiple media records after successful frontend uploads to R2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Batch confirm upload completion",
                "parameters": [
                    {
                        "description": "Batch confirm upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchConfirmUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchConfirmUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auto-post/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List auto-post generation logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "List auto-post logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by Setting ID",
                        "name": "settingId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (pending, success, failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoPostLogListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auto-post/logs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get auto-post log by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Get auto-post log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Log ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoPostLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auto-post/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List all auto-post settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "List auto-post settings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new auto-post setting for AI-powered automatic posting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Create auto-post setting",
                "parameters": [
                    {
                        "description": "Create auto-post setting request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAutoPostSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoPostSettingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auto-post/settings/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get auto-post setting by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Get auto-post setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Setting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoPostSettingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update auto-post setting by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Update auto-post setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Setting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update auto-post setting request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAutoPostSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoPostSettingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete auto-post setting by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Delete auto-post setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Setting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auto-post/settings/{id}/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Disable auto-post setting by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Disable auto-post setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Setting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auto-post/settings/{id}/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enable auto-post setting by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Enable auto-post setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Setting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/auto-post/settings/{id}/trigger": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manually trigger an auto-post generation for a specific setting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auto-post"
                ],
                "summary": "Trigger auto-post manually",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Setting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trigger auto-post request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.TriggerAutoPostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TriggerAutoPostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check overall system health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "System is healthy",
                        "schema": {
                            "$ref": "#/definitions/health.HealthCheck"
                        }
                    },
                    "503": {
                        "description": "System is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/health.HealthCheck"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Check if application is alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "Application is alive",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Check if application is ready to serve traffic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "Application is ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Application is not ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Get current application metrics including requests, response times, and status codes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get application metrics",
                "responses": {
                    "200": {
                        "description": "Current metrics",
                        "schema": {
                            "$ref": "#/definitions/metrics.MetricsSnapshot"
                        }
                    }
                }
            }
        },
        "/posts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new post with title, content, and media",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Create a new post",
                "parameters": [
                    {
                        "description": "Post data",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post created successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "Get a single post by ID with author and media information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Get post by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid post ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Post not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing post (author only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Update post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Post update data",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/simple-auto-post/queue": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get paginated list of queue items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simple-auto-post"
                ],
                "summary": "List queue items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (pending/completed/failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/simple-auto-post/queue/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get statistics about the auto-post queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simple-auto-post"
                ],
                "summary": "Get queue status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/simple-auto-post/setup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create the auto_post_queue table if it doesn't exist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simple-auto-post"
                ],
                "summary": "Setup auto-post queue table",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/simple-auto-post/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a CSV file with topics to add to auto-post queue",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simple-auto-post"
                ],
                "summary": "Upload CSV file to import topics",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file (format: category,topic,tone)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bot User ID (UUID)",
                        "name": "botUserId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UploadCSVResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AutoPostLogListResponse": {
            "type": "object",
            "properties": {
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AutoPostLogResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.PaginationMeta"
                }
            }
        },
        "dto.AutoPostLogResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "generatedTitle": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "post": {
                    "$ref": "#/definitions/dto.PostResponse"
                },
                "postId": {
                    "type": "string"
                },
                "settingId": {
                    "type": "string"
                },
                "status": {
                    "description": "pending, success, failed",
                    "type": "string"
                },
                "tokensUsed": {
                    "type": "integer"
                },
                "topic": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.AutoPostSettingResponse": {
            "type": "object",
            "properties": {
                "botUser": {
                    "$ref": "#/definitions/dto.UserResponse"
                },
                "botUserId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "cronSchedule": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "lastError": {
                    "type": "string"
                },
                "lastGeneratedAt": {
                    "type": "string"
                },
                "maxTokens": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "totalPostsGenerated": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.CreateAutoPostSettingRequest": {
            "type": "object",
            "required": [
                "botUserId",
                "cronSchedule",
                "topics"
            ],
            "properties": {
                "botUserId": {
                    "type": "string"
                },
                "cronSchedule": {
                    "description": "Cron expression",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 9
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "maxTokens": {
                    "type": "integer",
                    "maximum": 4000,
                    "minimum": 100
                },
                "model": {
                    "type": "string",
                    "enum": [
                        "gpt-4",
                        "gpt-4-turbo",
                        "gpt-3.5-turbo",
                        "gpt-4o",
                        "gpt-4o-mini"
                    ]
                },
                "topics": {
                    "type": "array",
                    "maxItems": 50,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.CreatePostRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "clientPostId": {
                    "description": "Client-generated unique ID for idempotency",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "content": {
                    "type": "string",
                    "maxLength": 40000,
                    "minLength": 1
                },
                "idempotencyKey": {
                    "description": "Idempotency key for caching responses",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "isDraft": {
                    "description": "true = save as draft (for video encoding)",
                    "type": "boolean"
                },
                "mediaIds": {
                    "description": "Max 10 media files per post",
                    "type": "array",
                    "maxItems": 10,
                    "items": {
                        "type": "string"
                    }
                },
                "sourcePostId": {
                    "description": "For crossposting",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 1
                }
            }
        },
        "dto.MediaResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "duration": {
                    "description": "For videos",
                    "type": "number"
                },
                "fileName": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "sourceId": {
                    "description": "ID of source entity",
                    "type": "string"
                },
                "sourceType": {
                    "description": "\"post\", \"message\", \"reel\", \"comment\"",
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "type": {
                    "description": "\"image\", \"video\", \"file\"",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "userId": {
                    "description": "Owner of the media",
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginationMeta": {
            "type": "object",
            "properties": {
                "hasMore": {
                    "description": "Whether more results exist (for search/filtered lists)",
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "description": "Exact total count (only if counted from DB)",
                    "type": "integer"
                }
            }
        },
        "dto.PostResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.UserResponse"
                },
                "commentCount": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "hotScore": {
                    "description": "For debugging/sorting",
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "isSaved": {
                    "description": "true/false",
                    "type": "boolean"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MediaResponse"
                    }
                },
                "sourcePost": {
                    "description": "For crossposts",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.PostResponse"
                        }
                    ]
                },
                "status": {
                    "description": "\"draft\" or \"published\"",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TagResponse"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "\"text\", \"image\", \"gallery\", \"video\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userVote": {
                    "description": "User-specific fields (when authenticated)",
                    "type": "string"
                },
                "votes": {
                    "type": "integer"
                }
            }
        },
        "dto.TagResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "postCount": {
                    "type": "integer"
                }
            }
        },
        "dto.TriggerAutoPostRequest": {
            "type": "object",
            "properties": {
                "topic": {
                    "description": "If empty, randomly select from configured topics",
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 3
                }
            }
        },
        "dto.TriggerAutoPostResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "log": {
                    "$ref": "#/definitions/dto.AutoPostLogResponse"
                },
                "post": {
                    "$ref": "#/definitions/dto.PostResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateAutoPostSettingRequest": {
            "type": "object",
            "properties": {
                "cronSchedule": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 9
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "maxTokens": {
                    "type": "integer",
                    "maximum": 4000,
                    "minimum": 100
                },
                "model": {
                    "type": "string",
                    "enum": [
                        "gpt-4",
                        "gpt-4-turbo",
                        "gpt-3.5-turbo",
                        "gpt-4o",
                        "gpt-4o-mini"
                    ]
                },
                "topics": {
                    "type": "array",
                    "maxItems": 50,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.UpdatePostRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 40000,
                    "minLength": 1
                },
                "tags": {
                    "type": "array",
                    "maxItems": 5,
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 1
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "description": "Only for owner",
                    "type": "string"
                },
                "followersCount": {
                    "type": "integer"
                },
                "followingCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isFollowing": {
                    "description": "Only when authenticated",
                    "type": "boolean"
                },
                "karma": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "handlers.BatchConfirmResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "fileKey": {
                    "type": "string"
                },
                "fileUrl": {
                    "type": "string"
                },
                "mediaId": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.BatchConfirmUploadRequest": {
            "type": "object",
            "required": [
                "uploads"
            ],
            "properties": {
                "uploads": {
                    "type": "array",
                    "maxItems": 200,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handlers.ConfirmUploadRequest"
                    }
                }
            }
        },
        "handlers.BatchConfirmUploadResponse": {
            "type": "object",
            "properties": {
                "failCount": {
                    "type": "integer"
                },
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.BatchConfirmResult"
                    }
                },
                "successCount": {
                    "type": "integer"
                },
                "successful": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.BatchConfirmResult"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.BatchPresignedUploadRequest": {
            "type": "object",
            "required": [
                "files"
            ],
            "properties": {
                "files": {
                    "type": "array",
                    "maxItems": 200,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handlers.PresignedUploadRequest"
                    }
                }
            }
        },
        "handlers.BatchPresignedUploadResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "uploads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PresignedUploadResponse"
                    }
                }
            }
        },
        "handlers.ConfirmUploadRequest": {
            "type": "object",
            "required": [
                "fileKey",
                "fileSize",
                "mediaId"
            ],
            "properties": {
                "contentType": {
                    "description": "MIME type",
                    "type": "string"
                },
                "duration": {
                    "description": "For videos (seconds)",
                    "type": "number"
                },
                "fileKey": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "height": {
                    "description": "For images/videos",
                    "type": "integer"
                },
                "mediaId": {
                    "type": "string"
                },
                "sourceId": {
                    "description": "ID of the source entity",
                    "type": "string"
                },
                "sourceType": {
                    "description": "\"post\", \"message\", \"reel\", etc.",
                    "type": "string"
                },
                "thumbnail": {
                    "description": "For videos",
                    "type": "string"
                },
                "width": {
                    "description": "For images/videos",
                    "type": "integer"
                }
            }
        },
        "handlers.PresignedUploadRequest": {
            "type": "object",
            "required": [
                "contentType",
                "fileSize",
                "filename",
                "mediaType"
            ],
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer",
                    "minimum": 1
                },
                "filename": {
                    "type": "string"
                },
                "mediaType": {
                    "type": "string",
                    "enum": [
                        "image",
                        "video",
                        "file"
                    ]
                }
            }
        },
        "handlers.PresignedUploadResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "description": "When the presigned URL expires",
                    "type": "string"
                },
                "fileKey": {
                    "description": "R2 object key",
                    "type": "string"
                },
                "fileUrl": {
                    "description": "Final public URL after upload",
                    "type": "string"
                },
                "mediaId": {
                    "description": "Media ID for tracking",
                    "type": "string"
                },
                "uploadUrl": {
                    "description": "Presigned URL for frontend to upload",
                    "type": "string"
                }
            }
        },
        "handlers.UploadCSVResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "totalFailed": {
                    "type": "integer"
                },
                "totalImported": {
                    "type": "integer"
                }
            }
        },
        "health.CheckResult": {
            "type": "object",
            "properties": {
                "duration": {
                    "description": "Swagger-compatible annotation",
                    "type": "string",
                    "example": "15ms"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/health.Status"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "health.HealthCheck": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/health.CheckResult"
                    }
                },
                "status": {
                    "$ref": "#/definitions/health.Status"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "health.Status": {
            "type": "string",
            "enum": [
                "healthy",
                "unhealthy",
                "degraded"
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusUnhealthy",
                "StatusDegraded"
            ]
        },
        "metrics.MetricsSnapshot": {
            "type": "object",
            "properties": {
                "avg_response_time_ms": {
                    "type": "number"
                },
                "custom_counters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "failed_requests": {
                    "type": "integer"
                },
                "max_response_time_ms": {
                    "type": "integer"
                },
                "min_response_time_ms": {
                    "type": "integer"
                },
                "status_2xx": {
                    "type": "integer"
                },
                "status_3xx": {
                    "type": "integer"
                },
                "status_4xx": {
                    "type": "integer"
                },
                "status_5xx": {
                    "type": "integer"
                },
                "successful_requests": {
                    "type": "integer"
                },
                "total_errors": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "utils.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/utils.ErrorDetail"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GoFiber Social Media API",
	Description:      "Social media platform backend API with real-time chat, posts, comments, and notifications",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
